function register(name, dbSize) {
    let d = {
        accountType: 1,
        constAccountType: 1,
        disableReason: '',
        display: name,
        name: name.toLowerCase().replaceAll(' ', '-'),
        skin: 'default',
        coins: 0,
        gems: 0,
        xp: 0,
        levelIcon: 1,
        challengeTier: 0,
        currentChallengeRequirements: {
            fistkills: 5,
            crowns: 15,
            winstreak: 3,
            blocks: 100,
            gamekills: 10,
            killstreak: 5,
            nodefwins: 0,
            toolwins: 0
        },
        currentChallengeProgress: {
            fistkills: 0,
            crowns: 0,
            winstreak: 0,
            blocks: 0,
            gamekills: 0,
            killstreak: 0,
            nodefwins: 0,
            toolwins: 0
        },
        kills: 0,
        deaths: 0,
        games: 0,
        wins: 0,
        winstreak: 0,
        crownDestroys: 0,
        inventory: {
            default: 1,
            default2: 1,
            constructionworker: 1,
            farmer: 1,
            sweating: 0,
            holdingtears: 0,
            grin: 0,
            joy: 0,
            rofl: 0,
            snail: 0,
            beetle: 0,
            cricket: 0,
            halo: 0,
            sunglasses: 0,
            suspicious: 0,
            sauropod: 0,
            orangutan: 0,
            parrot: 0,
            swan: 0,
            chipmunk: 0,
            nerd: 0,
            raisedeyebrow: 0,
            coldface: 0,
            imp: 0,
            pumpkin: 0,
            turkey: 0,
            dodo: 0,
            flamingo: 0,
            crocodile: 0,
            beaver: 0,
            flushed: 0,
            cowboy: 0,
            skull: 0,
            alien: 0,
            robot: 0,
            turtle: 0,
            dog: 0,
            cat: 0,
            rat: 0,
            peacock: 0,
            chicken: 0,
            rich: 0,
            killermouse: 0,
            spaceinvader: 0,
            femoby: 0,
            catfemoby: 0,
            rgbchicken: 0
        },
        lootboxes: {
            common: 0,
            good: 0,
            epic: 0,
            legendary: 0,
            mythic: 0
        },
        levelrewardsclaimed: [],
        badges: {
            mod: 0,
            verified: 0,
            crafter: 0,
            challenger: 0
        },
        settings: {
            embedcolor: 'blue',
            profileviews: false,
            anonymous: false
        },
        hcache: {
            save: false,
            map: 'ground',
            gamemode: 'Classic',
            fancyGarden: true,
            showIdentities: true,
            private: false,
            showEvents: true,
            showFps: false,
            respawnTime: 5000
        },
        analytics: {
            mostKills: 0,
            killsRanged: 0,
            killsMelee: 0,
            killsUtil: 0,
            dmgDealt: 0,
            dmgDealtBlocks: 0,
            blocksMined: 0,
            blocksPlaced: 0,
            itemsCrafted: 0,
            shots: 0,
            hits: 0,
            privateGames: 0,
            playtime: 0,
            playtimePrivate: 0,
            currentWinstreak: 0,
            highestWinstreak: 0
        },
        profileviews: 0,
        canUseRequest: true,
        requestTs: Date.now(),
        verifyNote: '',
        playerID: (dbSize || 0) + 1,
        created: Date.now(),
    };
    return d;
}

module.exports = { register };